REQUIRE
src/LabelledArrays.jl
src/slvector.jl
test/diffeq.jl
test/slvectors.jl

https://github.com/JuliaDiffEq/LabelledArrays.jl/pull/18#issuecomment-436278719
For the `@SLVector` macro, I modified @YingboMa's implementation to not return an anonymous constructor-like function but instead the type/constructor itself. This makes code much simpler (e.g. see the new slvectors.jl tests).
`similar(x)` and `AbstractFloat{T}(x)` still returns an unwrapped `MArray`. This is the behavior intended by StaticArrays (https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/abstractarray.jl#L94). I can probably make it better by defining a `MLVector` type, but for now this isn't really an issue.

Rewrite `SLVector` as a subtype of `StaticVector`

---

README.md
src/LabelledArrays.jl
src/larray.jl
src/slarray.jl
test/larrays.jl
test/runtests.jl
test/slarrays.jl

Allows conversion to and from named tuples. 
https://github.com/JuliaDiffEq/LabelledArrays.jl/issues/12#issuecomment-439719837
Not quite sure why `pairs` is not type stable though when defined as
```julia
Base.pairs(x::SLArray{S,N,Syms,T}) where {S,N,Syms,T} =
(label => getproperty(x, label) for label in Syms) # not type stable?
```
Same for `LArray`. Might have something to do with the generated `getindex` (the current version uses linear indexing instead)? Speaking of which, @ChrisRackauckas can you explain why
```julia
f(x) = x.a
@code_warntype f(x)
``` 
is ok in the tests but not `@code_warntype x.a` directly?

Named tuple conversion

---

src/slarray.jl
test/slarrays.jl

This PR generalizes the implementation of `similar_type` to new sizes of different lengths (in that case the returned type is a `SArray`).
Moreover, now `@SArray` and `@SVector` return more concrete types if element type, dimensions, and labels are provided (maybe that could/should be tried with the other macros as well since at least the number of dimensions and the size can be deduced, only the type of the elements is unspecified?).
Would it make sense to implement `mutable_similar_type` from StaticArrays as well, and depending on the size of the requested type let it return a `LArray` or a `MArray`?

Implement similar_type with different length

---

src/slarray.jl
test/slarrays.jl

This PR implements `similar` for `SLArray`, which depending on the desired length creates a `LArray` or a `MArray`. It feels slightly inconsistent since one case creates an `Array` whereas the other one creates a `StaticArray`. Maybe a `MLArray` would be more appropriate.

Implement similar for SLArray

---

README.md
src/LabelledArrays.jl
src/lsliced.jl
src/slarray.jl
src/slsliced.jl
test/lsliced.jl
test/runtests.jl
test/slarrays.jl
test/slsliced.jl

Attempt 2. This version just uses LArray and SLArtray with the sym tuples wrapped in a Tuple type.
SlicePartial allows partial getproperty. get/set methods dispatch on `Syms` being `<:Tuple{Syms1,Syms2}`

add slice labelled versions of LArray and SLArray

---

.gitignore
README.md
src/LabelledArrays.jl
src/larray.jl
src/lsliced.jl
src/slarray.jl
src/slsliced.jl
test/larrays.jl
test/lsliced.jl
test/slarrays.jl
test/slsliced.jl

implements #50 
Function `symbols` working on both `LArray` and `SLArray` return in a tuple of Symbols. For more dimensional names (providing a tuple of tuples to `LSliced`) it returns a `Tuple` object that is hard to handle. Therefore, I also implemented function `dimSymbols` that accesses the entry in this tuple in field `parameters`. Is there a better way?

access labels

---

.travis.yml
README.md
appveyor.yml
src/larray.jl
src/slarray.jl
test/larrays.jl
test/slarrays.jl

```julia
julia> EFG = @SLArray (2,2) (e=1:3, f=4, g=2:4);
julia> y = EFG(1.0,2.5,3.0,5.0)
2×2 SLArray{Tuple{2,2},Float64,2,4,(e = 1:3, f = 4, g = 2:4)}:
1.0  3.0
2.5  5.0
julia> y.g
3-element view(reshape(::StaticArrays.SArray{Tuple{2,2},Float64,2,4}, 4), 2:4) with eltype Float64:
2.5
3.0
5.0
julia> z = @LArray [1.,2.,3.] (a = 1:2, b = 2:3);
julia> z.b
2-element view(::Array{Float64,1}, 2:3) with eltype Float64:
2.0
3.0
```
is now possible.
CC: @jessebett

Add explicit indices handling via NamedTuple

---

src/slarray.jl

benchmarks on Pumas show that this does a tiny bit.

add some inlines

---

Project.toml
src/LabelledArrays.jl
src/larray.jl
test/REQUIRE

It turns out this is much faster than the fallback

Add copyto! overload

---

src/larray.jl
test/larrays.jl

The fallback for AbstractArrays calls `objectid` which will hash the complete object and that can be much more expensive than the `dataids(::Array)` which simply uses the pointer value.

Add fast version of Base.dataids for LArray

---

src/larray.jl
test/larrays.jl

...instead of the value that is being set. This is the usual interface
```julia
julia> setindex!(ones(3), 2, 1)
3-element Vector{Float64}:
2.0
1.0
1.0
```
The bracket syntax lowers specially to return the value instead
```
julia> ones(3)[1] = 2
2
julia> Meta.lower(Main, :(ones(3)[1] = 2))
:($(Expr(:thunk, CodeInfo(
@ none within `top-level scope'
1 ─ %1 = ones(3)
│        Base.setindex!(%1, 2, 1)
└──      return 2
))))
```

Make setindex! return the input array

---

Project.toml
src/LabelledArrays.jl
test/larrays.jl
test/slarrays.jl

Currently accessing a property that does not exist results in a `view` called on `nothing` since `idx` in the following snippet
https://github.com/SciML/LabelledArrays.jl/blob/10779c55925f426b3b91667611ee4f7156f0f059/src/LabelledArrays.jl#L9-L17
will be `nothing`. 
This can be quite confusing to debug, so I added a error with the same message as you'd get if you try to access a non-existent property of a struct, i.e. now you get:
```julia
julia> x = @LArray [1.0,2.0,3.0] (:a, :b, :c)
3-element LArray{Float64, 1, Vector{Float64}, (:a, :b, :c)}:
:a => 1.0
:b => 2.0
:c => 3.0
julia> x.d
ERROR: type LArray{Float64, 1, Vector{Float64}, (:a, :b, :c)} has no field d
[...]
```
rather than
```julia
julia> x = @LArray [1.0,2.0,3.0] (:a, :b, :c)
3-element LArray{Float64, 1, Vector{Float64}, (:a, :b, …
```

Error upon `getproperty` for nonexistent property

---

src/larray.jl
src/slarray.jl

to avoid deprecation error in Julia 1.7.

Use values(kwargs) instead of kwargs.data

---

Project.toml
src/LabelledArrays.jl
src/chainrules.jl
test/chainrules.jl
test/runtests.jl

This PR adds AD rules for:
- `LArray{syms}`
- `SLArray{size,syms}`
- `getproperty`
This all the issues in https://github.com/SciML/LabelledArrays.jl/issues/91 with the exception of the ForwardDiff.jl-issue for `SLArray`.
Some things of note/questions to address:

Adds `ChainRulesCore.rrule` for constructors and `getproperty`

---

src/larray.jl
test/larrays.jl

I noticed this when you asked if I meant `eltype`.
Not sure what I was thinking with that last PR/about the `gemv` test not getting it.
I'll need to rerun Pumas tests with this.
Anyway, now I'm at least comparing with `elsize` on a `Float64`.

Fix and properly test elsize

---

.github/workflows/Documentation.yml
.gitignore
docs/.gitignore
docs/Project.toml
docs/make.jl
docs/pages.jl
docs/src/Example_dsl.md
docs/src/LArrays.md
docs/src/NamedTuples_relation.md
docs/src/Note_labelled_slices.md
docs/src/SLArrays.md
docs/src/index.md

I created the basic skeleton for the docs. The basic pieces for `Documenter.jl` and the github workflow `Documenter.yml` are created. I wanted to make sure I am on the right track before proceeding any farther. 
One problem I ran into was a strange error when trying to test the development of the docs. I ran the usual code. 
```
julia --project=docs/ docs/make.jl
```
But for some reason I am getting an error below. Kinda a strange error since `Documenter` is not imported anywhere else. Have you hit this error before? Slack #helpdesk did not turn up any clues. 
```
WARNING: using Documenter.Documenter in module Main conflicts with an existing identifier.
ERROR: LoadError: importing Documenter into Main conflicts with an existing identifier
in expression starting at …
```

Add Documenter docs for LabelledArrays

---

Project.toml
src/LabelledArrays.jl
src/larray.jl
src/slarray.jl

This drops LabelledArrays.jl out of the DiffEq dependency tree.

Pick up a PreallocationTools.jl dependency

---

Project.toml
src/LabelledArrays.jl

Specifically when `get_tmp(cache::PreallocationTools.DiffCache, u:LArray{T, ...}` where T is _not_ a ForwardDiff.Dual, the method defined for Duals is used (which uses ArrayInterfaceCore.restructure --> allocations, even though we should just get the normal cache back, not the dual cache).
The changes introduced dispatch the present `get_tmp` only on Duals, so that for T <: Number the fallback method for u::AbstractArray in PreallocationTools is used (https://github.com/SciML/PreallocationTools.jl/blob/addfd170cb69f98778f7e5f40a3d9ab352c99b10/src/PreallocationTools.jl#L61)

Removes allocations with get_tmp that occur in some cases 

---

Project.toml
test/diffeq.jl
test/larrays.jl

Tests won't pass in CI because of a circular dependency with OrdinaryDiffEq. To test, remove it from Project.toml and comment out the diffeq tests.

chore: update RecursiveArrayTools compat

---

src/larray.jl
test/larrays.jl

Closes #93
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Add any other context about the problem here.

Remove erroneous `LVector` docstring and point user to the alternative that works.

---

.github/workflows/CI.yml
Project.toml
src/LabelledArrays.jl
src/diffeqarray.jl
test/recursivearraytools.jl
test/runtests.jl

[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Add any other context about the problem here.

refactor: add DiffEqArray constructor

---

README.md

This PR fixes a spelling error: additonal → additional.
- Fixed the misspelling of additional 
- Simple typo correction that doesn't affect functionality
-  included to avoid unnecessary CI runs for spelling fixes
- This is a clear spelling error correction

[ci skip] Fix spelling: additonal -> additional
